name: Deploy Jotto
on:
  push:
    tags:
      - 'jotto**'
      - 'all**'

jobs:
  deploy to staging:
    if: contains(${{  github.ref_name }}, 'staging')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        run: |
          echo "Deploying to staging"

  deploy to production:
    if: !contains(${{ github.ref_name }}, 'staging')
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production"