name: Deploy Jotto
on:
  push:
    tags:
      - 'jotto**'
      - 'all**'

env:
  APP_PATH: 'dist/apps/jotto/'

jobs:
  deploy-to-staging:
    if: "endsWith(github.ref_name, 'staging')"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        run: |
          echo "Deploying to staging $APP_PATH"

  deploy-to-production:
    if: "!endsWith(github.ref_name, 'staging')"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production"