name: Deploy Reach Labs
on:
  push:
    tags:
      - 'reach-labs**'
      - 'all**'

jobs:
  deploy-to-staging:
    if: "endsWith(github.ref_name, 'staging')"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging
        run: |
          echo "Deploying to staging"

  deploy-to-production:
    if: "!endsWith(github.ref_name, 'staging')"
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: |
          echo "Deploying to production"