name: Deploy Reach Labs
on:
  push:
    tags: 'reach-labs**staging'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying
        run: |
          echo "Deploying reach labs"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"